### ISSUE TITLE
Remember to add tensorflow in the requirement.txt

### ISSUE THREAD

**Issue by xinghua-qu** [rtaori/Black-Box-Audio#14]
I tried tensorflow 1.14 and it works. You may add that in your requirement.txt, which can benefit anyone else who is interested in your code:)

**Comment by StephenC808** [comment]
@QuXinghuaNTU  What version of deepspeech did you use may I ask? I am having trouble getting it to work

**Comment by xinghua-qu** [comment]
> @QuXinghuaNTU What version of deepspeech did you use may I ask? I am having trouble getting it to work

Think Rtaori has added the tensorflow version in requirements.txt. You can try again.
