### ISSUE TITLE
The full list of evaluated audios

### ISSUE THREAD

**Issue by xinghua-qu** [rtaori/Black-Box-Audio#16]
Could you please provide the full list of the evaluated audio? Currently, only three are available.

**Comment by rtaori** [comment]
Hi @QuXinghuaNTU,

Sorry, unfortunately it looks like they are not recoverable (I no longer have access to the system where the research was originally conducted). However, you should be able to regenerate any samples using the instructions in the README.

**Comment by xinghua-qu** [comment]
Noted with thanks.
