### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by jaeholo** [rtaori/Black-Box-Audio#18]
Hi！I am using an nvidia 3060 gpu and ubuntu 20.04, and the default cuda version for installation should be 11.4
I think maybe cuda9.0 is too old for this gpu, if I install cuda 11.4, will this code work?
Or should I downgrade my ubuntu to 16.04 to install the cuda9.0?

**Comment by rtaori** [comment]
Hi @jaeholo,

Unfortunately I have not been able to test the code out on cuda 11, so I have on idea if it will work or not. For the best setup, I would recommend installing cuda 9.0.

**Comment by jaeholo** [comment]
@rtaori Thank you! I think I would try cuda 11 first and I will tell you the result

**Comment by jaeholo** [comment]
@rtaori Hi! I think it cannot work with cuda11, since the deepspeech you used is based on tf1
