### ISSUE TITLE
time cost

### ISSUE THREAD

**Issue by jaeholo** [rtaori/Black-Box-Audio#19]
hi! I have run the attack file for about 40mins, it is now on the 200th iteration and still attacking.

Just wonder does this algorithm need so much time to attack or there is something wrong from me? How long should it take actually?

**Comment by rtaori** [comment]
Hi @jaeholo,

Yes, since this is a black box attack, it can be computationally intensive. Especially if your target transcription is long. Just to double check, do you see the output after every iteration? Does it change every now and then (to indicate it's working)?

**Comment by jaeholo** [comment]
@rtaori Yes it works, I have changed the target phrase to "and he knows it" and it only takes 20 iterations to finish attack.
