### ISSUE TITLE
Difference of two audio in sample

### ISSUE THREAD

**Issue by ccu1tn** [rtaori/Black-Box-Audio#25]
Dear author, 

I am listening to two audio files in your sample folder. (e.g. #1 - _he wasn't asking for help_ and #1_adv - _morning body_)
What is the meaning difference in here, sir? 
Please, Can you explain a little for me?

**Comment by rtaori** [comment]
Hi,
#1 refers to the original audio sample and its transcription, whereas #1_adv refers to the adversarial example and its transcription

**Comment by ccu1tn** [comment]
Dear author, 
Thank for you your reply, where is show this transcription in each interation when training or anywhere? 
but when I listened to audio #1_adv file, it still is "he wasn't asking for help".

**Comment by rtaori** [comment]
Yes, adversarial examples are designed to be imperceptible to humans. So it will still sound the same to you, but the ASR system will transcribe the audio as "morning body" instead.

**Comment by ccu1tn** [comment]
Thank you so much author, Which ASR system did you use to transcribe this audio?

**Comment by rtaori** [comment]
The same system that the adversarial attack was conducted on, DeepSpeech `https://github.com/mozilla/DeepSpeech/releases/download/v0.1.1/deepspeech-0.1.1-models.tar.gz
`

**Comment by ccu1tn** [comment]
Hi, 
I undersatood it. Thank you so much, sir.

**Comment by ccu1tn** [comment]
Dear Sir,
 I am still fusing about to calculate accuracy in your paper. 
 Can caculate that values based on the log_result file?
 Ex: Here is file log_result at iteration 1000/ 
 Accuracy is 98.8% right, sir? 
![image](https://github.com/rtaori/Black-Box-Audio/assets/43333942/8e0ec441-32bf-4c07-bdac-6fb81bd5082f)
Thank you so much for reply.!

**Comment by rtaori** [comment]
Hi,
0.998 is the correlation between the original audio file and the adversarially perturbed audio file. This is not the attack accuracy (accuracy is averaged over all the instances; this log file simply shows the correlation for a single file).

**Comment by ccu1tn** [comment]
Hi @rtaori , 
So, it's not the attack accuracy for that file, is it?
Could you please explain how you calculated the attack accuracy?

**Comment by rtaori** [comment]
Hi @ccu1tn,
The evaluation is described more precisely in section 3 here https://arxiv.org/pdf/1805.07820.pdf. Concretely, we measure the Levenshtein distance between the attacked audio (after 3k iterations) and the target transcription (we had 35% exact match).

**Comment by ccu1tn** [comment]
HI @rtaori,

Thank you so much again. I understool it.
