### ISSUE TITLE
about comparing with audio_adversarial_examples from carlini

### ISSUE THREAD

**Issue by TTTJJJWWW** [rtaori/Black-Box-Audio#3]
@rtaori Hi, thanks for your project.
I noticed that your project is very similar to another one(audio_adversarial_examples from carlini). I believe you referred to that project. So compared with that project, is your project exactly the same in terms of audio preprocessing(MFCC and the reverse of MFCC)? It's about the research I'm doing.
Look forward to your reply.

**Comment by rtaori** [comment]
@TTTJJJWWW Hi,
Yes we use the MFC preprocessing step (any input to the DeepSpeech model needs to be preprocessed as such). However, since our method is black box, there is no need for the reverse MFC.

**Comment by TTTJJJWWW** [comment]
@rtaori Hi,
I found that "models/session_dump" was used in "run_audio_attack.py", why the project need use it?
As a black-box-attack, why not use the the original model (from deepspeech) instead? 
Is the disturbance(or mutate) added before or after the MFCC process?

**Comment by rtaori** [comment]
We used it simply for ease of use. It was much easier to use the TF session, especially at the rate of samples we were passing through the model. The disturbances is added before the MFCC process.

**Comment by JeetShah10** [comment]
@rtaori @TTTJJJWWW While running run_audio_attack.py file,
saver.restore(sess, "models/session_dump") this line giving me an error of models; No such file or directory

saver.restore(sess, "models/session_dump")
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1536, in restore
if not checkpoint_management.checkpoint_exists(compat.as_text(save_path)):
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/checkpoint_management.py", line 364, in checkpoint_exists
if file_io.get_matching_files(pathname):
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 342, in get_matching_files
for single_filename in filename
File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in exit
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: models; No such file or directory

Can anyone help me with how can I resolve this error?

Thanks in advance.

**Comment by rtaori** [comment]
Hi @JeetShah10,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
