### ISSUE TITLE
error in make_checkpoint.py

### ISSUE THREAD

**Issue by karan306** [rtaori/Black-Box-Audio#4]
I got this error when i tried the following:
$ python3 make_checkpoint.py
Traceback (most recent call last):
  File "make_checkpoint.py", line 15, in <module>
    from util.audio import audiofile_to_input_vector
ModuleNotFoundError: No module named 'util.audio'
I have cloned Deepspeech in the same directory as make_checkpoint.py. Is there something else I need to do?

**Comment by rtaori** [comment]
Hi,
Thanks for pointing this out. It seems DeepSpeech team have refactored their repository recently. Please check out an older version of their project, as such:

`cd DeepSpeech`
`git checkout 033ee0f4c2b460b09e3de8725b5b8b2cc93717ec`

**Comment by rtaori** [comment]
Hi @karan306,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
