### ISSUE TITLE
error in run_audio_attack.py

### ISSUE THREAD

**Issue by shudong-zhang** [rtaori/Black-Box-Audio#5]
ValueError: Input tensor 'ExpandDims:0' enters the loop with shape (1, 11), but has shape (1, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.

When I run  run_audio_attack.py, I got an error list above.How to solve it ?

**Comment by rtaori** [comment]
Hi,
It seems the DeepSpeech repo has been updated since this work was done. Could you try following the suggestion in https://github.com/rtaori/Black-Box-Audio/issues/4 ?

**Comment by shudong-zhang** [comment]
I can pass the make_checkpoint.py, so I don't think the error casued by version.

**Comment by rtaori** [comment]
Right yes, but `run_audio_attack.py` still makes calls to the DeepSpeech library, so if anything there has changed then it could break the program. Could you try reverting to the commit specified in #4? I have tested it on that version so it should work.

**Comment by rtaori** [comment]
hi @zhangdong1992,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
