### ISSUE TITLE
question

### ISSUE THREAD

**Issue by NJW007** [rtaori/Black-Box-Audio#6]
ValueError: Input tensor 'ExpandDims:0' enters the loop with shape (1, 11), but has shape (1, ?) after one iteration. To allow the shape to vary across iterations, use the `shape_invariants` argument of tf.while_loop to specify a less-specific shape.
abc@abc-HP-El

what is the problem? thank you

**Comment by rtaori** [comment]
Hi,
It seems the DeepSpeech library has changed. Please follow the instructions in https://github.com/rtaori/Black-Box-Audio/issues/5 and https://github.com/rtaori/Black-Box-Audio/issues/4

**Comment by NJW007** [comment]
hello,I have done it as you said in #4,but it does‘t work.the error is as follows:
abc@abc-HP-EliteDesk-800-G3-TWR:~/njw/Audio-master/DeepSpeech$ git checkout 033ee0f4c2b460b09e3de8725b5b8b2cc93717ec
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).


so I worried  if I have done some wrong ways. the models is 0.1.0 and the code DeepSpeech is also 0.1.0 .Can you tall me what the wrong is?

**Comment by rtaori** [comment]
Did you `git clone https://github.com/mozilla/DeepSpeech.git` ?
It seems like your git directory has been corrupted. Maybe try recloning it?

**Comment by rtaori** [comment]
Hi @NJW007,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
