### ISSUE TITLE
Unknown command line flag 'alphabet_config_path'

### ISSUE THREAD

**Issue by zifanw** [rtaori/Black-Box-Audio#7]
Hey I am having this error for running make_checkpoint.py 

```
Traceback (most recent call last):
  File "make_checkpoint.py", line 49, in <module>
    tf.app.flags.FLAGS.alphabet_config_path = "DeepSpeech/data/alphabet.txt"
  File "/home/zifanw/env/lib/python3.6/site-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/home/zifanw/env/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/home/zifanw/env/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'alphabet_config_path'
```

can I know what version of TF you are using? Thx

**Comment by rtaori** [comment]
Hi,
Please use tensorflow-gpu==1.14
Thanks

**Comment by zifanw** [comment]
Thanks for replying. I actually use this version, but it won't let me pass. if you are using conda, could you share a env yapf file? Another change I made is that, I git chechout to the previous version, but however, for DeepSpeech < 0.5.0, their link for downloading ds_ctcdecoder is giving HTTP error. I have to use DeepSpeech 0.5.1 to successfully install ds_ctcdecoder. But I think this is not the version of DeepSpeech you are building on, right?

**Comment by rtaori** [comment]
Ah, I see. Yes, I use the 0.4 version. Could you try opening an issue on the DeepSpeech for the proper 0.4 link? 

I will try to see if the code can be updated to 0.5 in a few weeks

**Comment by zifanw** [comment]
Okay, I am raising an issue in their discussion page. Seems for version >0.5.1, they change a lot. Hopefully, you will succeed! 

Thx

**Comment by ruby11dog** [comment]
> Okay, I am raising an issue in their discussion page. Seems for version >0.5.1, they change a lot. Hopefully, you will succeed!
> 
> Thx

Do you fix that problem? I have the same issue.

**Comment by rtaori** [comment]
Hi @zifanw @ruby11dog,

I have updated the installation instructions with much more detail in the [README](https://github.com/rtaori/Black-Box-Audio#installation).
Please follow the steps there and open another issue if you still have any problems.
